### DISCUSSION TITLE
Pods associated with a deployment

### DISCUSSION THREAD

**Discussion by myoung841** [openshift/openshift-client-python#163] [Q&A]
Is there a specific way to list pods that are associated with a deployment? Perhaps a function that accepts a deployment name and returns a list of pods? The only way I've been able to do this so far is by using pattern matching to see if the pod name begins with the deployment name, which isn't really sufficient.

It's easy to do in the GUI (Click on the deployment and view the 'pods' tab) but I can't find a solid way of doing it using the CLI. Any help would be much appreciated.

**Comment by bradmwilliams** [comment]
Typically, this would be done via labels, defined as part of the Deployment, and then selecting the pods via a Label Selector.

For example:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```
Given the Deployment defined above, all the labels defined in `.spec.template.metadata.labels` would be applied any pods that correspond to this Deployment. 
So, the following logic could be used to get all the pods associated to this Deployment:

```
objs = oc.selector('pods', labels={'app': 'nginx'}).objects()
```
Hope this helps!
